---
- name: Installation de phantomjs pour génération du PDF
  package:
    name:
      - phantomjs
      - xvfb
    state: present

- name: Copie du fichier html
  template:
    src: index.html.j2
    dest: "{{ htmlresume_html_file }}"
  notify:
    - generate pdf

- name: Création d'un dossier pour le script phantomjs
  file:
    path: "{{ htmlresume_phantomjs_script_path }}"
    state: directory

- name: Copie du script phantomjs
  copy:
    src: htmltopdf.js
    dest: "{{ htmlresume_phantomjs_script_path }}"
