---
- name: Installation de phantomjs pour génération du PDF
  package:
    name: phantomjs
    state: present

- name: Copie du fichier html
  template:
    src: index.html.j2
    dest: "{{ htmlresume_webroot }}/index.html"
  notify:
    - generate pdf

- name: Création d'un dossier pour le script phantomjs
  file:
    path: /usr/local/share/phantomjs
    state: directory

- name: Copie du script phantomjs
  copy:
    src: htmltopdf.js
    dest: /usr/local/share/phantomjs
