---
- name: Ajout des libs pour la génération du PDF
  package:
    name: libfontconfig1
    state: present

- name: Copie du fichier html
  template:
    src: index.html.j2
    dest: "{{ htmlresume_webroot }}/index.html"
  notify:
    - generate pdf

- name: Récupération de phantomjs
  get_url:
    url: https://github.com/ariya/phantomjs/releases/download/2.1.3/phantomjs
    dest: "/usr/local/bin/"
    mode: 0775

- name: Création d'un dossier pour le script phantomjs
  file:
    path: /usr/local/share/phantomjs
    state: directory

- name: Copie du script phantomjs
  copy:
    src: htmltopdf.js
    dest: /usr/local/share/phantomjs
